### ISSUE TITLE
Add support to /mcstatus for embedding server icon

### ISSUE THREAD

**Issue by UvixCreative** [its-bens-fault/Discord-Bot#14]
This will probably be done through uploading the image to imgur. The problem is that the mcsrvstat.us API returns the icon in base64, but Discord doesn't seem to accept that.

Either 
- Use a CDN to host the images over HTTPS
- Figure out how to attach an image to a Discord "embed"

**Comment by CyborgPotato** [comment]
Have you looked at encoding a png after decoding the base64?

import { encode, decode } from "https://deno.land/std@0.162.0/encoding/base64.ts"
